name: Update Data and Notebook

# Controls when the workflow will run
on:
  # when the job should run; e.g. on push or on a schedule
  schedule:
    - cron:  '35,40 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  notebook_update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #env:
    # any environment variables needed
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: python -m pip install --upgrade pip -r docs/requirements.txt
      - name: Update analysis notebook
        run: |
          python -m pip install jupyter nbconvert nbformat
          jupyter nbconvert --to html --execute docs/source/notebook.ipynb --ExecutePreprocessor.kernel_name='python3' --output notebook_executed
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Plot update bot
          message: "Update Notebook"
          add: "notebook_executed.html"