name: Update Data and Notebook

on:
  schedule:
    - cron:  '55 * * * *'
  workflow_dispatch:
jobs:
  notebook_update:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # jupyter nbconvert --to html --execute docs/source/notebook.ipynb --ExecutePreprocessor.kernel_name='python3' --output notebook_executed
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: python -m pip install --upgrade pip -r docs/requirements.txt

      - name: Update analysis notebook
        run: |
          python -m pip install jupyter nbconvert nbformat
          jupyter nbconvert --to html --execute docs/source/notebook.ipynb --output notebook_executed.html
      
      - name: Commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub-Actions
          message: "Update Notebook"
          add: "*.html --force"
